name: release
on:
  release:
    types: [published]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bruceadams/get-release@v1.2.3
        id: release
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - uses: mymindstorm/setup-emsdk@v9
      - name: Release
        run: |
          git submodule init
          git submodule update
          npm i
          npm run build
          npm version from-git
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
